### ISSUE TITLE
Proposed quick fix for inability to alter existing sites

### ISSUE THREAD

**Issue by andybak** [quentinsf/ansible-webfaction#3]
In webfaction_site you have these comments:

```
# If it exists with the right I{, we don't change anything.
# Should check other parameters.
```

I hit exactly this issue. As a quick fix I was going to implement a new 'state' value - maybe called 'recreate'...

```
        if site_state == 'recreate':
            webfaction.delete_website(session_id, site_name, site_ip)
        else:
            module.exit_json(
                changed = False,
            )
```

Is this worth a pull request?

**Comment by quentinsf** [comment]
Hi Andy - 

First, thanks for alerting me to the rather embarrassing number of typos in the comments!  Now fixed.

Second, I've now implemented a check so that if the key site parameters change (https, subdomains or apps) it will call update_website instead of create_website.  

I think that fixes your issue?  

But it may be that you had the 'already exists with a different IP address' problem?  In that case we'd need to delete the site at whatever its existing address may be, and recreate it at the new one, and we should probably use a 'relocate=yes' or similar parameter, rather than a new state, because  you wouldn't normally want your script to make any changes if the site were already in the right place.

I've put some notes to this effect in the source, and I'll close this for now, but feel free to reopen if it hasn't solved your problem!

Quentin
